### ISSUE TITLE
Add HTTP API to expose services

### ISSUE THREAD

**Issue by switzersc** [switzersc/open_referral_transformer#9]
This should be a POST request that kicks off the `OpenReferralTransformer` class to process the provided files. The request can either be a multipart form request that streams that file contents to the API, or the request could reference the web URIs where the files live. If the latter, then the API needs to pass those URIs to the `OpenReferralTransformer` which should be able to get them during the transform process.

**Comment by switzersc** [comment]
You can use sinatra to add a simple http server: http://sinatrarb.com/

**Comment by andrewwang024** [comment]
curl -X POST -F "locations=C:\Users\andre\Documents\CS\open_referral_transformer\spec\fixtures\input\locations.csv" -F "organizations=C:\Users\andre\Documents\CS\open_referral_transformer\spec\fixtures\input\organizations.csv" -F "services=C:\Users\andre\Documents\CS\open_referral_transformer\spec\fixtures\input\services.csv" -F "mapping=C:\Users\andre\Documents\CS\open_referral_transformer\spec\fixtures\mapping.yaml" http://localhost:4567/transform

**Comment by switzersc** [comment]
Added with #32
